DEVICE_FOLDER := device/lenovo/K910L_43
USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/lenovo/K910L_43/BoardConfigVendor.mk

# Platform
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a9
TARGET_BOARD_PLATFORM := msm8974
TARGET_BOARD_PLATFORM_GPU := qcom-adreno330
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := krait
TARGET_USE_KRAIT_BIONIC_OPTIMIZATION := true
TARGET_BOOTLOADER_BOARD_NAME := MSM8974
TARGET_BOOTLOADER_BOARD_NAME := K910L_43
TARGET_OTA_ASSERT_DEVICE := K910L_43
TARGET_NO_BOOTLOADER := true
ARCH_ARM_HAVE_TLS_REGISTER := true
BOARD_HAS_NO_SELECT_BUTTON := true

# Kernel
BOARD_KERNEL_CMDLINE := console=tty60,115200,n8 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x01000000 --dt $(DEVICE_FOLDER)/recovery/dtb.img --tags_offset 0x00000100
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
TARGET_PREBUILT_KERNEL := $(DEVICE_FOLDER)/recovery/kernel
TARGET_PREBUILT_RECOVERY_KERNEL := $(DEVICE_FOLDER)/recovery/kernel
TARGET_RECOVERY_INITRC := $(DEVICE_FOLDER)/recovery/init.rc
TARGET_RECOVERY_FSTAB := $(DEVICE_FOLDER)/recovery/twrp.fstab

# File System
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00F00000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00F00000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x32000000
BOARD_CACHEIMAGE_PARTITION_SIZE := 0x8000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x100000000
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_FLASH_BLOCK_SIZE := 0x20000
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_NO_REAL_SDCARD := true

# Recovery
DEVICE_RESOLUTION := 1080x1920
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_23x41.h\"
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/msm_dwc3/f9200000.dwc3/gadget/lun%d/file
RECOVERY_GRAPHICS_USE_LINELENGTH := true

# Recovery TWRP
TW_INTERNAL_STORAGE_PATH := "/data/media"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"
TW_EXTERNAL_STORAGE_PATH := "/usb-otg"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "usb-otg"
TW_DOWNLOAD_MODE := true
TW_REBOOT_BOOTLOADER := true
RECOVERY_SDCARD_ON_DATA := true
TW_FLASH_FROM_STORAGE := true
#TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
#TW_CUSTOM_BATTERY_PATH := /sys/devices/qpnp-charger-f658ac00/power_supply/battery/capacity
TW_MAX_BRIGHTNESS := 255
TW_INCLUDE_FB2PNG := true
TWHAVE_SELINUX := true
